services:
  db:
    build: containers/mysql
    container_name: db
    restart: unless-stopped
    env_file: .env
    mem_limit: 512M
    cpus: 0.128
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    build:
      context: containers/wordpress
      args:
        IONCUBE_LOADER: "1"
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    mem_limit: 512M
    cpus: 0.512
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    build: containers/nginx
    container_name: webserver
    restart: unless-stopped
    mem_limit: 128M
    cpus: 0.512
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge
    external: true