services:
  db:
    platform: linux/amd64
    image: ghcr.io/gecut/lemp/mysql:8
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    platform: linux/amd64
    image: ghcr.io/gecut/lemp/wordpress:6
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    platform: linux/amd64
    image: ghcr.io/gecut/lemp/nginx:1
    container_name: webserver
    restart: unless-stopped
    ports:
      - "9090:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge