services:
  db:
    image: ghcr.io/gecut/lemp/mysql:8
    container_name: db
    restart: unless-stopped
    env_file: .env
    mem_limit: 512M
    cpus: 0.128
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: ghcr.io/gecut/lemp/wordpress:6.6-php8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    mem_limit: 512M
    cpus: 0.512
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    image: ghcr.io/gecut/lemp/nginx:1.27-alpine
    container_name: webserver
    restart: unless-stopped
    mem_limit: 128M
    cpus: 0.512
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge